name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: macos-latest
    steps:
      - name: Print Greeting
        run: echo "Hi there"
      - name: Print Bye
        run: echo "Bye"
